name: .NET

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
        fail-fast: false
        matrix:
            os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: |
          3.1.x
          5.0.x
          6.0.x
          7.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Generate Bindings
      run: dotnet run --project src/Flecs.NET.Bindgen
    - name: Build native libraries
      run: dotnet build src/Flecs.NET.Native
    - name: Run tests
      run: dotnet test --verbosity minimal
    - name: Pack Nuget packages
      run: |
        dotnet pack --property:FlecsAutoVersion=true -c Debug
        dotnet pack --property:FlecsAutoVersion=true -c Release
    - name: Upload artifacts
      if: matrix.os == 'ubuntu-latest'
      uses: actions/upload-artifact@v3
      with:
          name: Nuget Packages
          path: |
            src/**/*.nupkg
            src/**/*.snupkg
