# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
        fail-fast: false
        matrix:
            os: [ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v3
      with: 
        submodules: 'recursive'
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: | 
          3.1.x
          6.0.x
          7.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Generate Bindings
      run: dotnet run --project src/Flecs.NET.Bindgen
    - name: Build native libraries
      run: dotnet build src/Flecs.NET.Native
    - name: Run tests
      run: dotnet test
